// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAd92EXOmFQ2FherN-4Iye4Kw8HbGmkc8',
    appId: '1:93170296019:web:2586da4938f42ead102026',
    messagingSenderId: '93170296019',
    projectId: 'flutter-note-app-64c02',
    authDomain: 'flutter-note-app-64c02.firebaseapp.com',
    storageBucket: 'flutter-note-app-64c02.firebasestorage.app',
    measurementId: 'G-7JDBLTYS87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY3-73BCoXx7pXhb2gj047dQa4Ac7gOqI',
    appId: '1:93170296019:android:3f94e1842b3326d3102026',
    messagingSenderId: '93170296019',
    projectId: 'flutter-note-app-64c02',
    storageBucket: 'flutter-note-app-64c02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9QQTVn5m5alvZJysAft8zXmpb4us6dnc',
    appId: '1:93170296019:ios:f9c400ff1692cb2b102026',
    messagingSenderId: '93170296019',
    projectId: 'flutter-note-app-64c02',
    storageBucket: 'flutter-note-app-64c02.firebasestorage.app',
    iosBundleId: 'com.example.notesFlutterAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9QQTVn5m5alvZJysAft8zXmpb4us6dnc',
    appId: '1:93170296019:ios:f9c400ff1692cb2b102026',
    messagingSenderId: '93170296019',
    projectId: 'flutter-note-app-64c02',
    storageBucket: 'flutter-note-app-64c02.firebasestorage.app',
    iosBundleId: 'com.example.notesFlutterAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAd92EXOmFQ2FherN-4Iye4Kw8HbGmkc8',
    appId: '1:93170296019:web:75a409ce5935c9b7102026',
    messagingSenderId: '93170296019',
    projectId: 'flutter-note-app-64c02',
    authDomain: 'flutter-note-app-64c02.firebaseapp.com',
    storageBucket: 'flutter-note-app-64c02.firebasestorage.app',
    measurementId: 'G-KH69NB1V2N',
  );

}